Fix how wrapper scripts find target executables
The scripts now work when .bin is not on $PATH (which is probably the
case when direnv is not installed and active), when .bin has duplicate
leading entries on $PATH, and when $PATH does not contain the target
executable.

diff --git a/.bin/ls b/.bin/ls
--- a/.bin/ls
+++ b/.bin/ls
@@ -1,8 +1,15 @@
 #!/bin/sh
 ## Requires: coreutils
 
-# Grab the second `ls` in the $PATH (this script is the first)
-ls=`which -a ls | sed -n 2p`
+# Ignore this wrapper script
+bindir=`pwd | sed 's#\(/stow-dotfiles\)/.*#\1#'`/.bin
+ls=`which -a ls | grep -vxF "$bindir/ls" | head -n 1`
 
-# Assume GNU `ls`
-$ls --color=auto --group-directories-first -A ${1+"$@"}
+# Exit if there is no other ls executable on $PATH
+[ "X$ls" = X ] && {
+    echo >&2 'command not found: ls'
+    exit 1
+}
+
+# Output a directory listing with directories first, showing hidden files
+exec $ls --color=auto --group-directories-first -A ${1+"$@"}
diff --git a/.bin/tree b/.bin/tree
--- a/.bin/tree
+++ b/.bin/tree
@@ -1,7 +1,16 @@
 #!/bin/sh
 ## Requires: tree
 
-# Grab the second `tree` in the $PATH (this script is the first)
-tree=`which -a tree | sed -n 2p`
+# Ignore this wrapper script
+bindir=`pwd | sed 's#\(/stow-dotfiles\)/.*#\1#'`/.bin
+tree=`which -a tree | grep -vxF "$bindir/tree" | head -n 1`
 
-$tree --dirsfirst -a ${1+"$@"}
+# Exit if there is no other tree executable on $PATH
+[ "X$tree" = X ] && {
+    echo >&2 'command not found: tree'
+    exit 1
+}
+
+# Output a directory tree with directories first, showing hidden files
+[ -t 0 ] && set -- -C ${1+"$@"}
+exec $tree --dirsfirst -a ${1+"$@"}
